/* =========================================================
CONSTRUCTION PLAN SYSTEM — MASTER PLAN GENERATOR
---------------------------------------------------------
Coordinates all modular engines:

Plot
Setback
Buildable Footprint
Elevation
Section
CAD
Sheet

IMPORTANT:
This file must NOT create hard-coded rooms.
Room layout is generated by cadRenderer from payload.room_details.
========================================================= */

import {
  ConstructionPlanPayload,
  PlotShape,
} from "./types";

import {
  calculatePlotArea,
} from "./plotEngine";

import {
  calculateSetbacks,
} from "./setbackRules";

import {
  calculateBuildableFootprint,
} from "./layoutEngine";

import {
  calculateElevationProfile,
} from "./elevationEngine";

import {
  calculateSectionProfile,
} from "./sectionEngine";

import {
  prepareSheetLayout,
} from "./sheetEngine";

function safeNumber(
  value: unknown,
  fallback = 0
): number {
  const n = Number(value);

  return Number.isFinite(n)
    ? n
    : fallback;
}

export function generateCompleteConstructionPlan(
  payload: Partial<ConstructionPlanPayload> | any
) {
  const safePayload =
    payload || {};

  const dimensions =
    safePayload.dimensions || {
      A: 20,
      B: 20,
      C: 40,
      D: 40,
    };

  const plotShape =
    (
      safePayload.plot_shape ||
      "RECTANGULAR"
    ) as PlotShape;

  const roadSide =
    typeof safePayload.road_side ===
    "string"
      ? safePayload.road_side
      : "";

  const selectedFloors =
    Array.isArray(
      safePayload.selected_floors
    ) &&
    safePayload.selected_floors.length
      ? safePayload.selected_floors
      : ["GROUND FLOOR"];

  /*
  ---------------------------------------------------------
  PLOT
  ---------------------------------------------------------
  */

  const plotArea =
    safeNumber(
      safePayload.plot_area,
      calculatePlotArea(
        dimensions,
        plotShape
      )
    );

  /*
  ---------------------------------------------------------
  SETBACK
  ---------------------------------------------------------
  */

  const roadWidth =
    safeNumber(
      safePayload.road_width_feet,
      20
    );

  const isCorner =
    roadSide
      .toUpperCase()
      .includes("CORNER");

  const setbacks =
    calculateSetbacks(
      plotArea,
      roadWidth,
      isCorner
    );

  /*
  ---------------------------------------------------------
  BUILDABLE FOOTPRINT
  ---------------------------------------------------------
  */

  const footprint =
    calculateBuildableFootprint(
      dimensions,
      setbacks
    );

  /*
  ---------------------------------------------------------
  ELEVATION
  ---------------------------------------------------------
  */

  const floorHeight =
    safeNumber(
      safePayload.floor_height_feet,
      10
    );

  const elevation =
    calculateElevationProfile(
      selectedFloors,
      floorHeight
    );

  /*
  ---------------------------------------------------------
  SECTION
  ---------------------------------------------------------
  */

  const section =
    calculateSectionProfile(
      selectedFloors,
      floorHeight
    );

  /*
  ---------------------------------------------------------
  SHEET
  ---------------------------------------------------------
  */

  const sheetLayout =
    prepareSheetLayout({
      ...safePayload,

      plot_area:
        plotArea,

      total_builtup_area:
        safeNumber(
          safePayload.total_builtup_area,
          0
        ),

      total_room_area:
        safeNumber(
          safePayload.total_room_area,
          0
        ),
    } as ConstructionPlanPayload);

  return {
    plotArea,

    plotShape,

    dimensions,

    roadSide,

    selectedFloors,

    setbacks,

    footprint,

    elevation,

    section,

    sheetLayout,

    /*
    Keep these available to the preview
    and future engines.
    */

    floorDetails:
      safePayload.floor_details ||
      {},

    roomDetails:
      safePayload.room_details ||
      {},

    boundaries:
      safePayload.boundaries ||
      {},

    coverageType:
      safePayload.coverage_type ||
      "AS PER NORMS",
  };
}

